// src/app/views/forum-detail-view/forum-detail-view.component.ts
import { Component, inject, signal, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, RouterLink, Router } from '@angular/router';
import { DataService, Forum, Thread } from '../../services/data.service';
import { DEFAULT_USER_ID } from '../../config/user.config';
import { PageHeaderComponent } from '../../components/page-header/page-header.component';
import { TableSkeletonComponent } from '../../components/skeleton/table-skeleton.component';
import { EmptyStateComponent } from '../../components/empty-state/empty-state.component';
import { ErrorStateComponent } from '../../components/error-state/error-state.component';
import { TimeAgoComponent } from '../../components/time-ago/time-ago.component';
import { AvatarComponent } from '../../components/avatar/avatar.component';

@Component({
  selector: 'app-forum-detail-view',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink, PageHeaderComponent, TableSkeletonComponent, EmptyStateComponent, ErrorStateComponent, TimeAgoComponent, AvatarComponent],
  templateUrl: './forum-detail-view.component.html',
})
export class ForumDetailViewComponent implements OnInit {
  private route = inject(ActivatedRoute);
  private dataService = inject(DataService);
  private router = inject(Router);
  forum = signal<Forum | null>(null);
  threads = signal<Thread[]>([]);
  loading = signal(true);
  error = signal<string | null>(null);
  showNewThread = signal(false);
  newThreadTitle = '';
  newThreadBody = '';
  submitting = signal(false);
  submitError = signal<string | null>(null);

  ngOnInit() {
    this.load();
  }

  private load() {
    this.loading.set(true);
    this.error.set(null);
    const slug = this.route.snapshot.paramMap.get('slug') || '';
    this.dataService.getForums().subscribe({
      next: forums => {
        this.forum.set(forums.find(f => f.slug === slug) || null);
        this.dataService.getThreads(slug).subscribe({
          next: threads => {
            this.threads.set(threads);
            this.loading.set(false);
          },
          error: err => {
            this.error.set(err.message || 'Failed to load threads');
            this.loading.set(false);
          }
        });
      },
      error: err => {
        this.error.set(err.message || 'Failed to load forum');
        this.loading.set(false);
      }
    });
  }

  retry() {
    this.load();
  }

  formatDate(date: string) {
    return new Date(date).toLocaleString();
  }

  toggleNewThread() {
    this.showNewThread.update(v => !v);
    this.newThreadTitle = '';
    this.newThreadBody = '';
    this.submitError.set(null);
  }

  submitNewThread() {
    const slug = this.route.snapshot.paramMap.get('slug') || '';
    const title = this.newThreadTitle.trim();
    const body = this.newThreadBody.trim();
    if (!title || !body) return;

    this.submitting.set(true);
    this.submitError.set(null);

    this.dataService.createForumThread(slug, {
      title,
      body,
      postedById: DEFAULT_USER_ID,
    }).subscribe({
      next: ({ id: threadId }) => {
        this.submitting.set(false);
        this.showNewThread.set(false);
        this.newThreadTitle = '';
        this.newThreadBody = '';
        this.router.navigate(['/forums', slug, threadId]);
      },
      error: err => {
        this.submitting.set(false);
        this.submitError.set(err.message || 'Failed to create thread');
      }
    });
  }
}

<div class="max-w-5xl mx-auto">
  <app-table-skeleton *ngIf="loading()" [cols]="3" [rows]="6"></app-table-skeleton>

  <app-error-state *ngIf="error() && !loading()" title="Failed to load forum" [description]="error()!" (retry)="retry()"></app-error-state>

  <ng-container *ngIf="!loading() && !error() && forum()">
    <app-page-header [title]="forum()!.name" [description]="forum()!.description" [count]="threads().length" [showAction]="true" actionLabel="New Thread" (action)="toggleNewThread()"></app-page-header>

    <!-- New Thread Form -->
    <div *ngIf="showNewThread()" class="app-panel p-4 mb-4 border-primary-300 dark:border-primary-700">
      <h3 class="text-sm font-semibold text-gray-900 dark:text-gray-100 mb-3">Create a new thread</h3>
      <div class="space-y-3">
        <div>
          <label for="new-thread-title" class="block text-xs font-medium text-gray-700 dark:text-gray-300 mb-1">Title</label>
          <input
            id="new-thread-title"
            type="text"
            [(ngModel)]="newThreadTitle"
            class="w-full rounded border border-gray-200 dark:border-gray-600 dark:bg-gray-900 dark:text-gray-100 px-2 py-1.5 text-sm focus:border-primary-500 focus:ring-1 focus:ring-primary-500 outline-none"
            placeholder="Thread title"
            required
          />
        </div>
        <div>
          <label for="new-thread-body" class="block text-xs font-medium text-gray-700 dark:text-gray-300 mb-1">Body</label>
          <textarea
            id="new-thread-body"
            [(ngModel)]="newThreadBody"
            rows="4"
            class="w-full resize-none rounded border border-gray-200 dark:border-gray-600 dark:bg-gray-900 dark:text-gray-100 px-2 py-1.5 text-sm focus:border-primary-500 focus:ring-1 focus:ring-primary-500 outline-none"
            placeholder="Optional body content..."
          ></textarea>
        </div>
        <div *ngIf="submitError()" class="text-xs text-red-600 dark:text-red-400 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-900/30 rounded px-3 py-2">{{ submitError() }}</div>
        <div class="flex items-center justify-end gap-2">
          <button type="button" (click)="toggleNewThread()" class="px-3 py-1.5 text-xs font-medium text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-200 transition-colors">Cancel</button>
          <button
            (click)="submitNewThread()"
            [disabled]="submitting() || !newThreadTitle.trim() || !newThreadBody.trim()"
            class="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-white bg-primary-600 hover:bg-primary-700 disabled:opacity-50 disabled:cursor-not-allowed rounded transition-colors"
          >
            <svg *ngIf="submitting()" class="animate-spin h-3.5 w-3.5" fill="none" viewBox="0 0 24 24">
              <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
              <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
            </svg>
            {{ submitting() ? 'Posting...' : 'Create Thread' }}
          </button>
        </div>
      </div>
    </div>

    <app-empty-state *ngIf="threads().length === 0" title="No threads" description="Publish the first thread to get the conversation started."></app-empty-state>

    <div *ngIf="threads().length > 0" class="app-panel overflow-hidden">
      <div class="overflow-x-auto">
      <table class="app-table">
        <thead>
          <tr>
            <th>Topic</th>
            <th class="w-24 text-center">Replies</th>
            <th class="w-40 text-right">Last Activity</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let thread of threads()" [routerLink]="['/forums', forum()!.slug, thread.id]" class="hover:cursor-pointer">
            <td>
              <div class="flex items-center gap-3">
                <app-avatar [name]="thread.author.name" [size]="32"></app-avatar>
                <div class="min-w-0">
                  <span class="app-link font-medium">{{ thread.title }}</span>
                  <div class="text-xs text-gray-400 mt-0.5">by {{ thread.author.name }} on {{ formatDate(thread.createdAt) }}</div>
                </div>
              </div>
            </td>
            <td class="text-center text-sm text-gray-500 dark:text-gray-400">{{ thread.replyCount }}</td>
            <td class="text-right text-xs text-gray-400">
              <app-time-ago *ngIf="thread.lastReplyAt" [date]="thread.lastReplyAt"></app-time-ago>
              <span *ngIf="!thread.lastReplyAt">—</span>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    </div>
  </ng-container>
</div>

// src/views/ForumDetailView.tsx
import React, { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { MessageSquare, Plus, ArrowLeft, Eye, Clock, X, Send, MessagesSquare } from 'lucide-react';
import { PageHeader } from '../components/PageHeader';
import { Avatar } from '../components/Avatar';
import { EmptyState } from '../components/EmptyState';
import { dataService } from '../services/dataService';
import { useToast } from '../context/ToastContext';
import { Forum, Thread } from '../types';

export const ForumDetailView: React.FC = () => {
  const { slug } = useParams<{ slug: string }>();
  const [forum, setForum] = useState<Forum | null>(null);
  const [threads, setThreads] = useState<Thread[]>([]);
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [title, setTitle] = useState('');
  const [body, setBody] = useState('');
  const { showToast } = useToast();

  useEffect(() => {
    if (slug) {
      const allForums = dataService.getForums();
      const current = allForums.find((f) => f.slug === slug);
      if (current) setForum(current);
      setThreads(dataService.getThreads(slug));
    }
  }, [slug]);

  const handleCreateThread = (e: React.FormEvent) => {
    e.preventDefault();
    if (!title.trim() || !slug) return;
    dataService.createThread(slug, { title: title.trim(), body: body.trim() });
    setTitle('');
    setBody('');
    setShowCreateModal(false);
    showToast('Thread created successfully!', 'success');
    setThreads(dataService.getThreads(slug));
  };

  const formatSlugToTitle = (s?: string) => {
    if (!s) return 'Forum Discussions';
    return s
      .split('-')
      .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
      .join(' ');
  };

  const forumName = forum ? forum.name : formatSlugToTitle(slug);
  const forumDescription = forum ? forum.description : `Discussion threads and open questions for ${forumName}.`;

  return (
    <div className="max-w-5xl mx-auto py-6 px-4 space-y-6">
      <div className="flex items-center gap-2 text-xs text-slate-500 dark:text-slate-400">
        <Link to="/forums" className="hover:text-indigo-600 dark:hover:text-indigo-400 flex items-center gap-1 transition-colors">
          <ArrowLeft className="w-3.5 h-3.5" />
          <span>Forums</span>
        </Link>
        <span>/</span>
        <span className="text-slate-900 dark:text-white font-medium">{forumName}</span>
      </div>

      <PageHeader
        title={forumName}
        subtitle={forumDescription}
        action={
          <button
            onClick={() => setShowCreateModal(true)}
            className="inline-flex items-center gap-1.5 px-3.5 py-1.5 bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold rounded-lg shadow-sm transition-all shrink-0 cursor-pointer"
          >
            <Plus className="w-4 h-4" />
            <span>New Thread</span>
          </button>
        }
      />

      {/* Threads List */}
      <div className="space-y-3">
        {threads.length === 0 ? (
          <EmptyState
            icon={MessagesSquare}
            title="No Threads in this Forum Yet"
            description="Be the first to open a discussion thread, query architectural guidelines, or propose a change."
            actionLabel="Create First Thread"
            onAction={() => setShowCreateModal(true)}
          />
        ) : (
          threads.map((thread) => (
            <Link
              key={thread.id}
              to={`/forums/${slug || thread.forum.slug}/${thread.id}`}
              className="group block bg-white dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700/80 hover:border-indigo-500/60 dark:hover:border-indigo-500/60 rounded-xl p-4 transition-all shadow-xs"
            >
              <div className="flex items-start justify-between gap-4">
                <div className="flex items-start gap-3">
                  <Avatar name={thread.author.name} avatar={thread.author.avatar} size="md" />
                  <div className="space-y-1">
                    <h3 className="text-sm font-bold text-slate-900 dark:text-white group-hover:text-indigo-600 dark:group-hover:text-indigo-300 transition-colors font-poppins">
                      {thread.title}
                    </h3>
                    <p className="text-xs text-slate-600 dark:text-slate-300 line-clamp-2 leading-relaxed">{thread.body}</p>
                    <div className="flex items-center gap-3 text-[11px] text-slate-400 dark:text-slate-500 pt-1 font-mono">
                      <span>By {thread.author.name}</span>
                      <span>•</span>
                      <span>{new Date(thread.createdAt).toLocaleDateString()}</span>
                    </div>
                  </div>
                </div>

                <div className="flex items-center gap-4 text-xs text-slate-500 dark:text-slate-400 shrink-0 font-mono">
                  <div className="flex items-center gap-1">
                    <MessageSquare className="w-3.5 h-3.5 text-indigo-500 dark:text-indigo-400" />
                    <span>{thread.replyCount}</span>
                  </div>
                  <div className="flex items-center gap-1">
                    <Eye className="w-3.5 h-3.5 text-slate-400" />
                    <span>{thread.viewCount}</span>
                  </div>
                </div>
              </div>
            </Link>
          ))
        )}
      </div>

      {/* Create Thread Modal */}
      {showCreateModal && (
        <div className="fixed inset-0 z-50 bg-slate-900/60 dark:bg-slate-950/80 backdrop-blur-sm flex items-center justify-center p-4">
          <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-xl max-w-lg w-full p-5 space-y-4 shadow-2xl text-slate-900 dark:text-slate-100">
            <div className="flex items-center justify-between border-b border-slate-200 dark:border-slate-800 pb-3">
              <h3 className="text-sm font-bold text-slate-900 dark:text-white font-poppins">New Discussion Thread</h3>
              <button
                onClick={() => setShowCreateModal(false)}
                className="text-slate-400 hover:text-slate-600 dark:hover:text-white"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            <form onSubmit={handleCreateThread} className="space-y-4">
              <div>
                <label className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1">Thread Title</label>
                <input
                  type="text"
                  required
                  value={title}
                  onChange={(e) => setTitle(e.target.value)}
                  placeholder="Summarize your question or topic..."
                  className="w-full h-9 px-3 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-lg text-xs text-slate-900 dark:text-slate-100 placeholder-slate-400 focus:outline-none focus:border-indigo-500 dark:focus:border-indigo-400"
                />
              </div>

              <div>
                <label className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1">Content / Details</label>
                <textarea
                  rows={5}
                  required
                  value={body}
                  onChange={(e) => setBody(e.target.value)}
                  placeholder="Provide complete context..."
                  className="w-full p-3 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-lg text-xs text-slate-900 dark:text-slate-100 placeholder-slate-400 focus:outline-none focus:border-indigo-500 dark:focus:border-indigo-400 resize-none"
                />
              </div>

              <div className="flex justify-end gap-2 pt-2 border-t border-slate-200 dark:border-slate-800">
                <button
                  type="button"
                  onClick={() => setShowCreateModal(false)}
                  className="px-3 py-1.5 text-xs text-slate-500 dark:text-slate-400 hover:text-slate-800 dark:hover:text-white"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-4 py-1.5 bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold rounded-lg shadow-sm"
                >
                  Post Thread
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};
