// src/app/views/plan-detail-view/plan-detail-view.component.ts
import { Component, OnInit, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { DataService, Plan } from '../../services/data.service';

import { StatusBadgeComponent } from '../../components/status-badge/status-badge.component';
import { RaiseQuestionComponent } from '../../components/raise-question/raise-question.component';
import { SkeletonComponent } from '../../components/skeleton/skeleton.component';
import { ErrorStateComponent } from '../../components/error-state/error-state.component';
import { MarkdownRendererComponent } from '../../components/markdown-renderer/markdown-renderer.component';

@Component({
  selector: 'app-plan-detail-view',
  standalone: true,
  imports: [CommonModule, RouterLink, StatusBadgeComponent, RaiseQuestionComponent, SkeletonComponent, ErrorStateComponent, MarkdownRendererComponent],
  templateUrl: './plan-detail-view.component.html',
})
export class PlanDetailViewComponent implements OnInit {
  private route = inject(ActivatedRoute);
  private dataService = inject(DataService);

  plan = signal<Plan | null>(null);
  loading = signal(true);
  error = signal<string | null>(null);

  ngOnInit() {
    this.route.paramMap.subscribe(params => {
      const id = params.get('id') || '';
      this.load(id);
    });
  }

  private load(id: string) {
    this.loading.set(true);
    this.error.set(null);
    this.dataService.getPlan(id).subscribe({
      next: plan => {
        this.plan.set(plan);
        this.loading.set(false);
      },
      error: err => {
        this.error.set(err.message || 'Failed to load plan');
        this.loading.set(false);
      }
    });
  }

  retry() {
    const id = this.route.snapshot.paramMap.get('id') || '';
    this.load(id);
  }

  parseJson(value: string): unknown {
    try {
      return JSON.parse(value);
    } catch {
      return value;
    }
  }

  formatJson(value: unknown): string {
    return JSON.stringify(value, null, 2);
  }
}

<div class="max-w-4xl mx-auto">
  <div *ngIf="loading()" class="space-y-4">
    <div class="app-panel p-4 space-y-2">
      <app-skeleton width="40%" height="1rem"></app-skeleton>
      <app-skeleton width="20%" height="0.75rem"></app-skeleton>
    </div>
    <div class="app-panel p-4 space-y-3">
      <app-skeleton width="30%" height="0.75rem"></app-skeleton>
      <app-skeleton width="100%" height="0.875rem"></app-skeleton>
    </div>
  </div>

  <app-error-state *ngIf="error() && !loading()" title="Failed to load plan" [description]="error()!" (retry)="retry()"></app-error-state>

  <ng-container *ngIf="!loading() && !error() && plan()">
    <div class="flex items-center gap-2 text-xs text-gray-500 dark:text-gray-400 mb-3">
      <a [routerLink]="['/plans']" class="hover:text-primary-700 transition-colors">Plans</a>
      <span>/</span>
      <span class="text-gray-700 dark:text-gray-300 font-medium truncate">{{ plan()!.title || 'Untitled' }}</span>
    </div>

    <div class="app-panel p-4 mb-4">
      <div class="flex items-start justify-between gap-4">
        <div class="min-w-0 flex-1">
          <h1 class="text-lg font-bold text-gray-900 dark:text-gray-100">{{ plan()!.title || 'Untitled' }}</h1>
          <div class="flex items-center gap-2 mt-2 flex-wrap">
            <span class="font-mono text-xs text-gray-500 dark:text-gray-400">{{ plan()!.id.slice(0, 8) }}…</span>
            <app-status-badge [status]="plan()!.status"></app-status-badge>
          </div>
        </div>
        <app-raise-question objectType="plan" [objectId]="plan()!.id" [objectTitle]="plan()!.title || 'Untitled'"></app-raise-question>
      </div>
    </div>

    <div class="grid grid-cols-1 lg:grid-cols-3 gap-4">
      <div class="lg:col-span-2 space-y-4">
        <div class="app-panel p-4">
          <h2 class="text-sm font-semibold text-gray-900 dark:text-gray-100 mb-2">Goal</h2>
          <div *ngIf="plan()!.goal; else noGoal" class="prose prose-sm max-w-none">
            <app-markdown-renderer [content]="plan()!.goal || ''"></app-markdown-renderer>
          </div>
          <ng-template #noGoal>
            <p class="text-sm text-gray-500 dark:text-gray-400">No goal recorded.</p>
          </ng-template>
        </div>

        <div *ngIf="plan()!.content" class="app-panel p-4">
          <h2 class="text-sm font-semibold text-gray-900 dark:text-gray-100 mb-2">Content</h2>
          <div class="prose prose-sm max-w-none">
            <app-markdown-renderer [content]="plan()!.content || ''"></app-markdown-renderer>
          </div>
        </div>

        <div *ngIf="plan()!.acceptanceCriteria && plan()!.acceptanceCriteria !== '[]'" class="app-panel p-4">
          <h2 class="text-sm font-semibold text-gray-900 dark:text-gray-100 mb-2">Acceptance Criteria</h2>
          <pre class="bg-gray-50 dark:bg-steel-800/80 dark:text-steel-200 p-3 rounded text-xs font-mono overflow-auto max-h-64 whitespace-pre-wrap">{{ formatJson(parseJson(plan()!.acceptanceCriteria)) }}</pre>
        </div>

        <div *ngIf="plan()!.dependencies && plan()!.dependencies !== '[]'" class="app-panel p-4">
          <h2 class="text-sm font-semibold text-gray-900 dark:text-gray-100 mb-2">Dependencies</h2>
          <pre class="bg-gray-50 dark:bg-steel-800/80 dark:text-steel-200 p-3 rounded text-xs font-mono overflow-auto max-h-64 whitespace-pre-wrap">{{ formatJson(parseJson(plan()!.dependencies)) }}</pre>
        </div>

        <div *ngIf="plan()!.filesAffected && plan()!.filesAffected !== '[]'" class="app-panel p-4">
          <h2 class="text-sm font-semibold text-gray-900 dark:text-gray-100 mb-2">Files Affected</h2>
          <pre class="bg-gray-50 dark:bg-steel-800/80 dark:text-steel-200 p-3 rounded text-xs font-mono overflow-auto max-h-64 whitespace-pre-wrap">{{ formatJson(parseJson(plan()!.filesAffected)) }}</pre>
        </div>
      </div>

      <div class="space-y-4">
        <div class="app-panel p-4">
          <h2 class="text-sm font-semibold text-gray-900 dark:text-gray-100 mb-2">Plan Metadata</h2>
          <div class="space-y-2 text-sm">
            <div>
              <span class="text-gray-500 dark:text-gray-400">Project:</span>
              <span class="ml-1 text-gray-900 dark:text-gray-100">{{ plan()!.project || '—' }}</span>
            </div>
            <div>
              <span class="text-gray-500 dark:text-gray-400">File:</span>
              <span class="ml-1 font-mono text-xs text-gray-700 dark:text-gray-300">{{ plan()!.fileName || '—' }}</span>
            </div>
            <div>
              <span class="text-gray-500 dark:text-gray-400">Prompt Ref:</span>
              <span class="ml-1 text-gray-900 dark:text-gray-100">{{ plan()!.promptRef || '—' }}</span>
            </div>
            <div>
              <span class="text-gray-500 dark:text-gray-400">Created:</span>
              <span class="ml-1 text-gray-900 dark:text-gray-100">{{ plan()!.createdAt | date:'medium' }}</span>
            </div>
            <div>
              <span class="text-gray-500 dark:text-gray-400">Updated:</span>
              <span class="ml-1 text-gray-900 dark:text-gray-100">{{ plan()!.updatedAt | date:'medium' }}</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </ng-container>
</div>

// src/views/PlanDetailView.tsx
import React, { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { ArrowLeft, CheckSquare, FileText } from 'lucide-react';
import { PageHeader } from '../components/PageHeader';
import { StatusBadge } from '../components/StatusBadge';
import { MarkdownRenderer } from '../components/MarkdownRenderer';
import { dataService } from '../services/dataService';
import { formatDateTime } from '../utils/format';
import { Plan } from '../types';

export const PlanDetailView: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const [plan, setPlan] = useState<Plan | null>(null);

  useEffect(() => {
    if (id) {
      const item = dataService.getPlan(id);
      if (item) setPlan(item);
    }
  }, [id]);

  if (!plan) {
    return (
      <div className="max-w-4xl mx-auto py-8 text-center text-slate-400">
        <p>Plan not found</p>
        <Link to="/plans" className="text-sm text-indigo-400 hover:underline mt-2 inline-block">
          Return to Plans
        </Link>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto py-6 px-4 space-y-6">
      <div className="flex items-center gap-2 text-sm text-slate-500 dark:text-slate-400">
        <Link to="/plans" className="hover:text-indigo-400 flex items-center gap-1">
          <ArrowLeft className="w-3.5 h-3.5" />
          <span>Plans</span>
        </Link>
        <span>/</span>
        <Link to={`/plans/${plan.id}`} className="text-slate-900 dark:text-white font-mono hover:text-indigo-600 dark:hover:text-indigo-400 hover:underline">{plan.id}</Link>
      </div>

      <PageHeader
        title={plan.title}
        subtitle={`Project: ${plan.project} • File: ${plan.fileName}`}
        ttsContent={`Plan ${plan.title}. Goal: ${plan.goal}. Content: ${plan.content}`}
        action={<StatusBadge status={plan.status} size="md" />}
      />

      <div className="app-panel p-4 space-y-5">
        <div>
          <h3 className="text-sm font-bold text-slate-400 uppercase tracking-wider font-mono mb-1">Goal</h3>
          <MarkdownRenderer content={plan.goal || ''} />
        </div>

        <div>
          <h3 className="text-sm font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider font-mono mb-1">Acceptance Criteria</h3>
          <p className="text-sm text-emerald-700 dark:text-emerald-300 bg-emerald-50 dark:bg-emerald-950/40 p-3 rounded-lg border border-emerald-200 dark:border-emerald-500/30">
            {plan.acceptanceCriteria}
          </p>
        </div>

        <div>
          <h3 className="text-sm font-bold text-slate-400 uppercase tracking-wider font-mono mb-1">Content Markdown</h3>
          <MarkdownRenderer content={plan.content || ''} />
        </div>

        <div className="grid grid-cols-2 gap-4 text-sm font-mono border-t border-slate-200 dark:border-slate-700/60 pt-4">
          <div>
            <span className="text-slate-500 dark:text-slate-400 block text-[11px]">Files Affected</span>
            <span className="text-indigo-600 dark:text-indigo-300 font-bold">{plan.filesAffected}</span>
          </div>
          <div>
            <span className="text-slate-500 dark:text-slate-400 block text-[11px]">Prompt Reference</span>
            <span className="text-slate-700 dark:text-slate-200">{plan.promptRef}</span>
          </div>
          <div>
            <span className="text-slate-500 dark:text-slate-400 block text-[11px]">Created</span>
            <span className="text-slate-700 dark:text-slate-200">{plan.createdAt ? formatDateTime(plan.createdAt) : '—'}</span>
          </div>
          <div>
            <span className="text-slate-500 dark:text-slate-400 block text-[11px]">Updated</span>
            <span className="text-slate-700 dark:text-slate-200">{plan.updatedAt ? formatDateTime(plan.updatedAt) : '—'}</span>
          </div>
        </div>
      </div>
    </div>
  );
};
