// src/app/views/specification-detail-view/specification-detail-view.component.ts
import { Component, inject, signal, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { DataService, Specification, OpenQuestion } from '../../services/data.service';

import { RaiseQuestionComponent } from '../../components/raise-question/raise-question.component';
import { SkeletonComponent } from '../../components/skeleton/skeleton.component';
import { ErrorStateComponent } from '../../components/error-state/error-state.component';
import { StatusBadgeComponent } from '../../components/status-badge/status-badge.component';

@Component({
  selector: 'app-specification-detail-view',
  standalone: true,
  imports: [CommonModule, RouterLink, RaiseQuestionComponent, SkeletonComponent, ErrorStateComponent, StatusBadgeComponent],
  templateUrl: './specification-detail-view.component.html',
})
export class SpecificationDetailViewComponent implements OnInit {
  private route = inject(ActivatedRoute);
  private dataService = inject(DataService);

  specification = signal<Specification | null>(null);
  openQuestions = signal<OpenQuestion[]>([]);
  loading = signal(true);
  error = signal<string | null>(null);

  ngOnInit() {
    this.route.paramMap.subscribe(params => {
      const id = params.get('id') || '';
      this.load(id);
    });
  }

  private load(id: string) {
    this.loading.set(true);
    this.error.set(null);
    this.dataService.getSpecification(id).subscribe({
      next: spec => {
        this.specification.set(spec);
        this.dataService.getOpenQuestionsForEntity('specification', id).subscribe({
          next: res => {
            this.openQuestions.set(res.items);
            this.loading.set(false);
          },
          error: () => {
            this.loading.set(false);
          }
        });
      },
      error: err => {
        this.error.set(err.message || 'Failed to load specification');
        this.loading.set(false);
      }
    });
  }

  retry() {
    const id = this.route.snapshot.paramMap.get('id') || '';
    this.load(id);
  }

  formatJson(value: Record<string, unknown> | null): string {
    return JSON.stringify(value, null, 2);
  }

  formatDate(date: string): string {
    return new Date(date).toLocaleString();
  }
}

<div class="max-w-4xl mx-auto">
  <div *ngIf="loading()" class="space-y-4">
    <div class="app-panel p-4 space-y-2">
      <app-skeleton width="40%" height="1rem"></app-skeleton>
      <app-skeleton width="20%" height="0.75rem"></app-skeleton>
    </div>
    <div class="app-panel p-4 space-y-3">
      <app-skeleton width="30%" height="0.75rem"></app-skeleton>
      <app-skeleton width="100%" height="0.875rem"></app-skeleton>
    </div>
  </div>

  <app-error-state *ngIf="error() && !loading()" title="Failed to load specification" [description]="error()!" (retry)="retry()"></app-error-state>

  <ng-container *ngIf="!loading() && !error() && specification()">
    <div class="flex items-center gap-2 text-xs text-gray-500 dark:text-gray-400 mb-3">
      <a [routerLink]="['/specifications']" class="hover:text-primary-700 transition-colors">Specifications</a>
      <span>/</span>
      <span class="text-gray-700 dark:text-gray-300 font-medium truncate">Revision #{{ specification()!.revisionNumber }}</span>
    </div>

    <div class="app-panel p-4 mb-4">
      <div class="flex items-start justify-between gap-4">
        <div class="min-w-0 flex-1">
          <h1 class="text-lg font-bold text-gray-900 dark:text-gray-100">Revision #{{ specification()!.revisionNumber }}</h1>
          <div class="flex items-center gap-2 mt-2 flex-wrap">
            <span class="font-mono text-xs text-gray-500 dark:text-gray-400">{{ specification()!.id.slice(0, 8) }}…</span>
            <span class="text-xs px-1.5 py-0.5 rounded bg-steel-100 dark:bg-steel-700 text-steel-700 dark:text-steel-300 border border-steel-200 dark:border-steel-600">{{ specification()!.revisionType }}</span>
          </div>
        </div>
        <app-raise-question objectType="specification" [objectId]="specification()!.id" [objectTitle]="'Revision #' + specification()!.revisionNumber"></app-raise-question>
      </div>
    </div>

    <div class="grid grid-cols-1 lg:grid-cols-3 gap-4">
      <div class="lg:col-span-2 space-y-4">
        <div *ngIf="specification()!.changeSummary" class="app-panel p-4">
          <h2 class="text-sm font-semibold text-gray-900 dark:text-gray-100 mb-2">Change Summary</h2>
          <p class="text-sm text-gray-700 whitespace-pre-wrap">{{ specification()!.changeSummary }}</p>
        </div>

        <div *ngIf="specification()!.itemSnapshot" class="app-panel p-4">
          <h2 class="text-sm font-semibold text-gray-900 dark:text-gray-100 mb-2">Item Snapshot</h2>
          <pre class="bg-gray-50 dark:bg-steel-800/80 dark:text-steel-200 p-3 rounded text-xs font-mono overflow-auto max-h-96 whitespace-pre-wrap">{{ formatJson(specification()!.itemSnapshot) }}</pre>
        </div>

        <div *ngIf="specification()!.derivedFrom?.length" class="app-panel p-4">
          <h2 class="text-sm font-semibold text-gray-900 dark:text-gray-100 mb-2">Derived From</h2>
          <ul class="space-y-1">
            <li *ngFor="let source of specification()!.derivedFrom" class="text-sm font-mono text-gray-700 dark:text-gray-300">{{ source }}</li>
          </ul>
        </div>
      </div>

      <div class="space-y-4">
        <div class="app-panel p-4">
          <h2 class="text-sm font-semibold text-gray-900 dark:text-gray-100 mb-2">Details</h2>
          <dl class="space-y-2 text-sm">
            <div>
              <dt class="text-xs text-gray-500 uppercase">Agenda</dt>
              <dd>
                <a [routerLink]="['/agendas', specification()!.agendaId]" class="app-link font-mono text-xs">{{ specification()!.agendaId.slice(0, 8) }}…</a>
              </dd>
            </div>
            <div>
              <dt class="text-xs text-gray-500 uppercase">Valid From</dt>
              <dd class="text-gray-700 dark:text-gray-300">{{ formatDate(specification()!.validFrom) }}</dd>
            </div>
            <div>
              <dt class="text-xs text-gray-500 uppercase">Valid Until</dt>
              <dd class="text-gray-700 dark:text-gray-300">{{ formatDate(specification()!.validUntil) }}</dd>
            </div>
            <div>
              <dt class="text-xs text-gray-500 uppercase">Created</dt>
              <dd class="text-gray-700 dark:text-gray-300">{{ formatDate(specification()!.createdAt) }}</dd>
            </div>
            <div *ngIf="specification()!.supersededBy">
              <dt class="text-xs text-gray-500 uppercase">Superseded By</dt>
              <dd>
                <a [routerLink]="['/specifications', specification()!.supersededBy]" class="app-link font-mono text-xs">{{ specification()!.supersededBy!.slice(0, 8) }}…</a>
              </dd>
            </div>
          </dl>
        </div>

        <div class="app-panel p-4">
          <h2 class="text-sm font-semibold text-gray-900 dark:text-gray-100 mb-2">Related Open Questions</h2>
          <div *ngIf="openQuestions().length === 0" class="text-sm text-gray-500 dark:text-gray-400">No open questions linked.</div>
          <div *ngIf="openQuestions().length > 0" class="divide-y divide-gray-100 dark:divide-gray-700/50">
            <a *ngFor="let oq of openQuestions()" [routerLink]="['/open-questions', oq.id]" class="block py-2 hover:bg-steel-100 dark:hover:bg-steel-700/40 transition-colors">
              <div class="text-sm font-medium text-gray-900 dark:text-gray-100">{{ oq.title }}</div>
              <app-status-badge [status]="oq.status"></app-status-badge>
            </a>
          </div>
        </div>
      </div>
    </div>
  </ng-container>
</div>

// src/views/SpecificationDetailView.tsx
import React, { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { ArrowLeft, FileCheck } from 'lucide-react';
import { PageHeader } from '../components/PageHeader';
import { dataService } from '../services/dataService';
import { formatDateTime } from '../utils/format';
import { Specification } from '../types';

export const SpecificationDetailView: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const [spec, setSpec] = useState<Specification | null>(null);

  useEffect(() => {
    if (id) {
      const item = dataService.getSpecification(id);
      if (item) setSpec(item);
    }
  }, [id]);

  if (!spec) {
    return (
      <div className="max-w-4xl mx-auto py-8 text-center text-slate-400">
        <p>Specification not found</p>
        <Link to="/specifications" className="text-sm text-indigo-400 hover:underline mt-2 inline-block">
          Return to Specifications
        </Link>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto py-6 px-4 space-y-6">
      <div className="flex items-center gap-2 text-sm text-slate-500 dark:text-slate-400">
        <Link to="/specifications" className="hover:text-indigo-400 flex items-center gap-1">
          <ArrowLeft className="w-3.5 h-3.5" />
          <span>Specifications</span>
        </Link>
        <span>/</span>
        <Link to={`/specifications/${spec.id}`} className="text-slate-900 dark:text-white font-mono hover:text-indigo-600 dark:hover:text-indigo-400 hover:underline">{spec.id}</Link>
      </div>

      <PageHeader
        title={<>Specification <Link to={`/specifications/${spec.id}`} className="text-indigo-600 dark:text-indigo-400 hover:underline font-mono">{spec.id}</Link></>}
        subtitle={`Revision ${spec.revisionNumber} (${spec.revisionType})`}
        ttsContent={`Specification ${spec.id}. ${spec.changeSummary || ''}`}
      />

      <div className="app-panel p-4 space-y-4">
        <h3 className="text-sm font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider font-mono">Change Summary</h3>
        <p className="text-sm text-slate-700 dark:text-slate-200 leading-relaxed">{spec.changeSummary}</p>

        <div className="grid grid-cols-3 gap-4 pt-3 border-t border-slate-200 dark:border-slate-700 text-sm font-mono">
          <div>
            <span className="text-slate-500 dark:text-slate-400 block text-[11px]">Valid From</span>
            <span className="text-slate-700 dark:text-slate-200">{spec.validFrom ? formatDateTime(spec.validFrom) : '—'}</span>
          </div>
          <div>
            <span className="text-slate-500 dark:text-slate-400 block text-[11px]">Valid Until</span>
            <span className="text-slate-700 dark:text-slate-200">{spec.validUntil ? formatDateTime(spec.validUntil) : '—'}</span>
          </div>
          <div>
            <span className="text-slate-500 dark:text-slate-400 block text-[11px]">Created</span>
            <span className="text-slate-700 dark:text-slate-200">{spec.createdAt ? formatDateTime(spec.createdAt) : '—'}</span>
          </div>
        </div>

        {spec.derivedFrom && spec.derivedFrom.length > 0 && (
          <div className="pt-3 border-t border-slate-200 dark:border-slate-700">
            <h3 className="text-sm font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider font-mono mb-2">Derived From</h3>
            <ul className="space-y-1">
              {spec.derivedFrom.map((source) => (
                <li key={source} className="text-sm font-mono text-slate-600 dark:text-slate-300">{source}</li>
              ))}
            </ul>
          </div>
        )}

        <h3 className="text-sm font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider font-mono pt-3 border-t border-slate-200 dark:border-slate-700">
          Item Snapshot Data
        </h3>
        <div className="bg-slate-50 dark:bg-slate-900 p-4 rounded-lg font-mono text-sm text-slate-700 dark:text-indigo-300 overflow-x-auto border border-slate-200 dark:border-slate-700/60">
          <pre>{JSON.stringify(spec.itemSnapshot, null, 2)}</pre>
        </div>
      </div>
    </div>
  );
};
