// src/views/ThreadDetailView.tsx
import React, { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { Send, CornerDownRight } from 'lucide-react';
import { Avatar } from '../components/Avatar';
import { TTSButton } from '../components/TTSButton';
import { MarkdownRenderer } from '../components/MarkdownRenderer';
import { dataService } from '../services/dataService';
import { formatDateTime } from '../utils/format';
import { useToast } from '../context/ToastContext';
import { Thread, Comment } from '../types';

export const ThreadDetailView: React.FC = () => {
  const { slug, threadId } = useParams<{ slug: string; threadId: string }>();
  const [thread, setThread] = useState<Thread | null>(null);
  const [comments, setComments] = useState<Comment[]>([]);
  const [replyText, setReplyText] = useState('');
  const [replyingToId, setReplyingToId] = useState<string | null>(null);
  const { showToast } = useToast();

  const loadData = () => {
    if (!threadId) return;
    // Warm the per-forum thread cache (live mode keeps threads per slug in liveCache,
    // so getThreads(slug) populates it synchronously before getThread is consulted).
    if (slug) dataService.getThreads(slug);
    const res = dataService.getThread(threadId);
    if (res.thread) setThread(res.thread);
    if (res.comments.length) setComments(res.comments);
    // In live mode the API fetch resolves asynchronously into the cache after this
    // synchronous read — re-read shortly after so cold deep-links render too.
    // Always re-check in live mode because comments are loaded async via api.fetchThread()
    // which populates the cache after the initial synchronous return.
    const isLiveMode = (import.meta.env.ASSEMBLY_MODE || 'mock') === 'live';
    if (isLiveMode && !res.comments.length) {
      // In live mode, if comments are empty, keep checking until they load (with safety limit)
      let attempts = 0;
      const maxAttempts = 10;
      const checkComments = () => {
        attempts++;
        const r2 = dataService.getThread(threadId);
        if (r2.comments.length) {
          setComments(r2.comments);
        } else if (attempts < maxAttempts) {
          // Try again after a delay
          window.setTimeout(checkComments, 300);
        }
      };
      window.setTimeout(checkComments, 300);
    } else if (!res.thread && !res.comments.length) {
      // In mock mode, only re-check if both are empty
      window.setTimeout(() => {
        const r2 = dataService.getThread(threadId);
        if (r2.thread) setThread(r2.thread);
        if (r2.comments.length) setComments(r2.comments);
      }, 900);
    }
  };

  useEffect(() => {
    loadData();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [threadId, slug]);

  const handlePostComment = (e: React.FormEvent, parentId?: string | null) => {
    e.preventDefault();
    if (!replyText.trim() || !threadId) return;

    dataService.addComment(threadId, {
      body: replyText.trim(),
      parentId: parentId || null,
    });
    setReplyText('');
    setReplyingToId(null);
    showToast('Reply added successfully!', 'success');
    loadData();
  };

  // Threaded comment tree, mirroring the Angular template's rootComments()/childComments().
  const rootComments = comments.filter((c) => !c.parentId);
  const childComments = (parentId: string) => comments.filter((c) => c.parentId === parentId);

  const CommentBody: React.FC<{ comment: Comment; nested: boolean }> = ({ comment, nested }) => (
    <>
      <div className="flex items-center gap-2">
        <Avatar name={comment.author.name} avatar={comment.author.avatar} size="sm" />
        <div className="text-xs text-gray-500 dark:text-gray-400">
          <span className="font-medium text-gray-700 dark:text-gray-300">{comment.author.name}</span>
          <span className="ml-1">
            {formatDateTime(comment.createdAt)}
          </span>
        </div>
      </div>
      <div className={`mt-1 ${nested ? 'ml-7' : 'ml-9'}`}>
        <MarkdownRenderer content={comment.body} />
        <button
          onClick={() => setReplyingToId(replyingToId === comment.id ? null : comment.id)}
          className="mt-1.5 inline-flex items-center gap-1 text-[11px] text-gray-500 dark:text-gray-400 hover:text-primary-600 dark:hover:text-primary-300 transition-colors"
        >
          <CornerDownRight className="w-3 h-3" />
          Reply
        </button>
      </div>
      {replyingToId === comment.id && (
        <form onSubmit={(e) => handlePostComment(e, comment.id)} className={`mt-2 space-y-2 ${nested ? 'ml-7' : 'ml-9'}`}>
          <label htmlFor={`reply-to-${comment.id}`} className="sr-only">Reply to {comment.author.name}</label>
          <textarea
            id={`reply-to-${comment.id}`}
            value={replyText}
            onChange={(e) => setReplyText(e.target.value)}
            placeholder={`Replying to ${comment.author.name}...`}
            rows={2}
            className="w-full bg-white dark:bg-steel-900 border border-steel-200 dark:border-steel-700 rounded-lg p-2.5 text-sm text-steel-900 dark:text-steel-100 placeholder-steel-400 focus:outline-none focus:border-primary-500 resize-none"
          />
          <div className="flex justify-end gap-2">
            <button
              type="button"
              onClick={() => setReplyingToId(null)}
              className="px-3 py-1 text-sm text-gray-500 dark:text-gray-400 hover:text-gray-800 dark:hover:text-white"
            >
              Cancel
            </button>
            <button type="submit" disabled={!replyText.trim()} className="app-btn-primary disabled:opacity-50">
              Send Reply
            </button>
          </div>
        </form>
      )}
    </>
  );

  if (!thread) {
    return (
      <div className="max-w-4xl mx-auto py-12 px-4 text-center text-steel-500 dark:text-steel-400 space-y-3">
        <p className="text-sm font-semibold text-steel-800 dark:text-steel-200">Thread not found</p>
        <Link
          to={`/forums/${slug || 'issues-and-open-questions'}`}
          className="text-sm text-primary-600 dark:text-primary-400 hover:underline inline-block font-medium"
        >
          Return to Forum
        </Link>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto py-6 px-4">
      <div className="flex items-center gap-2 text-xs text-gray-500 dark:text-gray-400 mb-3">
        <Link to="/forums" className="hover:text-primary-700 dark:hover:text-primary-300 transition-colors">
          Forums
        </Link>
        <span>/</span>
        <Link to={`/forums/${thread.forum.slug}`} className="hover:text-primary-700 dark:hover:text-primary-300 transition-colors">
          {thread.forum.name}
        </Link>
      </div>

      {/* Main Thread Card (document) */}
      <div className="app-panel p-4 mb-4">
        <div className="flex items-start justify-between gap-4">
          <h1 className="text-lg font-bold text-gray-900 dark:text-gray-100">{thread.title}</h1>
          <TTSButton text={`${thread.title}. ${thread.body}`} label="Read Thread" />
        </div>
        <div className="flex items-center gap-2 mt-3">
          <Avatar name={thread.author.name} avatar={thread.author.avatar} size="md" />
          <div className="text-xs text-gray-500 dark:text-gray-400">
            <span className="font-medium text-gray-700 dark:text-gray-300">{thread.author.name}</span>
            <span className="ml-1">{formatDateTime(thread.createdAt)}</span>
          </div>
        </div>
        <div className="mt-4">
          <MarkdownRenderer content={thread.body} />
        </div>
      </div>

      {/* Reply Form (document) — new root comment */}
      <form onSubmit={(e) => handlePostComment(e, null)} className="app-panel p-3 mb-4">
        <h3 className="text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase mb-2">Add a comment</h3>
        <label htmlFor="td-new-comment" className="sr-only">Add a comment</label>
        <textarea
          id="td-new-comment"
          value={replyingToId ? '' : replyText}
          onChange={(e) => {
            setReplyingToId(null);
            setReplyText(e.target.value);
          }}
          placeholder="Write your constructive response..."
          rows={2}
          className="w-full resize-none rounded border border-steel-200 dark:border-steel-700 dark:bg-steel-900 dark:text-steel-100 p-2 text-sm focus:border-primary-500 focus:ring-1 focus:ring-primary-500 outline-none bg-white text-steel-800"
        />
        <div className="flex items-center justify-end gap-2 mt-2">
          <button
            type="submit"
            disabled={!replyText.trim() || !!replyingToId}
            className="app-btn-primary disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <Send className="w-3.5 h-3.5" />
            Post Comment
          </button>
        </div>
      </form>

      {/* Comments (threaded) */}
      <h2 className="text-sm font-semibold text-gray-900 dark:text-gray-100 mb-2">Comments ({comments.length})</h2>
      {comments.length === 0 ? (
        <div className="app-panel p-6 text-center text-sm text-gray-400 dark:text-gray-500">
          <p className="font-medium text-gray-600 dark:text-gray-300">No comments</p>
          <p className="mt-1">Be the first to comment on this thread.</p>
        </div>
      ) : (
        <div className="space-y-3">
          {rootComments.map((comment) => (
            <div key={comment.id} className="app-panel p-3">
              <CommentBody comment={comment} nested={false} />

              {/* Threaded replies */}
              {childComments(comment.id).length > 0 && (
                <div className="ml-9 mt-2 space-y-2 border-l-2 border-gray-100 dark:border-gray-700 pl-3">
                  {childComments(comment.id).map((child) => (
                    <div key={child.id} className="py-1.5">
                      <CommentBody comment={child} nested />
                    </div>
                  ))}
                </div>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

// src/app/views/thread-detail-view/thread-detail-view.component.ts
import { Component, inject, signal, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { DataService, Thread, Comment } from '../../services/data.service';
import { DEFAULT_USER_ID } from '../../config/user.config';
import { RaiseQuestionComponent } from '../../components/raise-question/raise-question.component';
import { SkeletonComponent } from '../../components/skeleton/skeleton.component';
import { EmptyStateComponent } from '../../components/empty-state/empty-state.component';
import { ErrorStateComponent } from '../../components/error-state/error-state.component';
import { MarkdownRendererComponent } from '../../components/markdown-renderer/markdown-renderer.component';
import { TimeAgoComponent } from '../../components/time-ago/time-ago.component';
import { AvatarComponent } from '../../components/avatar/avatar.component';

@Component({
  selector: 'app-thread-detail-view',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink, RaiseQuestionComponent, SkeletonComponent, EmptyStateComponent, ErrorStateComponent, MarkdownRendererComponent, TimeAgoComponent, AvatarComponent],
  templateUrl: './thread-detail-view.component.html',
})
export class ThreadDetailViewComponent implements OnInit {
  private route = inject(ActivatedRoute);
  private dataService = inject(DataService);
  thread = signal<Thread | null>(null);
  comments = signal<Comment[]>([]);
  replyBody = '';
  replyToCommentId = signal<string | null>(null);
  replyToAuthor = signal<string | null>(null);
  loading = signal(true);
  error = signal<string | null>(null);

  ngOnInit() {
    this.load();
  }

  private load() {
    this.loading.set(true);
    this.error.set(null);
    const threadId = this.route.snapshot.paramMap.get('threadId') || '';
    this.dataService.getThread(threadId).subscribe({
      next: ({ thread, comments }) => {
        this.thread.set(thread);
        this.comments.set(comments);
        this.loading.set(false);
      },
      error: err => {
        this.error.set(err.message || 'Failed to load thread');
        this.loading.set(false);
      }
    });
  }

  retry() {
    this.load();
  }

  formatDate(date: string) {
    return new Date(date).toLocaleString();
  }

  replyTo(comment: Comment) {
    this.replyToCommentId.set(comment.id);
    this.replyToAuthor.set(comment.author.name);
    this.replyBody = `@${comment.author.name} `;
  }

  cancelReply() {
    this.replyToCommentId.set(null);
    this.replyToAuthor.set(null);
    this.replyBody = '';
  }

  submitReply() {
    if (!this.replyBody.trim() || !this.thread()) return;
    const threadId = this.route.snapshot.paramMap.get('threadId') || '';
    const postedById = DEFAULT_USER_ID;
    const parentId = this.replyToCommentId() || undefined;
    this.dataService.createComment(threadId, { body: this.replyBody.trim(), postedById, parentId }).subscribe({
      next: () => {
        this.replyBody = '';
        this.replyToCommentId.set(null);
        this.replyToAuthor.set(null);
        this.load();
      },
      error: err => {
        this.error.set(err.message || 'Failed to post reply');
      }
    });
  }

  childComments(parentId: string): Comment[] {
    return this.comments().filter(c => c.parentId === parentId);
  }

  rootComments(): Comment[] {
    return this.comments().filter(c => !c.parentId);
  }
}

<div class="max-w-4xl mx-auto">
  <div *ngIf="loading()" class="space-y-3">
    <div class="app-panel p-4 space-y-3">
      <app-skeleton width="40%" height="1rem"></app-skeleton>
      <app-skeleton width="20%" height="0.75rem"></app-skeleton>
      <app-skeleton width="100%" height="4rem"></app-skeleton>
    </div>
    <div *ngFor="let _ of [1,2]" class="app-panel p-3 space-y-2">
      <app-skeleton width="30%" height="0.75rem"></app-skeleton>
      <app-skeleton width="90%" height="0.875rem"></app-skeleton>
    </div>
  </div>

  <app-error-state *ngIf="error() && !loading()" title="Failed to load thread" [description]="error()!" (retry)="retry()"></app-error-state>

  <ng-container *ngIf="!loading() && !error() && thread()">
    <div class="flex items-center gap-2 text-xs text-gray-500 dark:text-gray-400 mb-3">
      <a [routerLink]="['/forums']" class="hover:text-primary-700 transition-colors">Forums</a>
      <span>/</span>
      <a [routerLink]="['/forums', thread()!.forum.slug]" class="hover:text-primary-700 transition-colors">{{ thread()!.forum.name }}</a>
    </div>
    <div class="app-panel p-4 mb-4">
      <h1 class="text-lg font-bold text-gray-900 dark:text-gray-100">{{ thread()!.title }}</h1>
      <div class="flex items-center gap-2 mt-3">
        <app-avatar [name]="thread()!.author.name" [size]="32"></app-avatar>
        <div class="text-xs text-gray-500 dark:text-gray-400">
          <span class="font-medium text-gray-700 dark:text-gray-300">{{ thread()!.author.name }}</span>
          <app-time-ago [date]="thread()!.createdAt"></app-time-ago>
        </div>
      </div>
      <div class="mt-4">
        <app-markdown-renderer [content]="thread()!.body"></app-markdown-renderer>
      </div>
      <div class="mt-4">
        <app-raise-question objectType="thread" [objectId]="thread()!.id" [objectTitle]="thread()!.title"></app-raise-question>
      </div>
    </div>

    <h2 class="text-sm font-semibold text-gray-900 dark:text-gray-100 mb-2">Comments ({{ comments().length }})</h2>
    <app-empty-state *ngIf="comments().length === 0" title="No comments" description="Be the first to comment on this thread."></app-empty-state>
    <div class="space-y-3">
      <!-- Root comments -->
      <div *ngFor="let comment of rootComments()" class="app-panel p-3">
        <div class="flex items-center gap-2">
          <app-avatar [name]="comment.author.name" [size]="28"></app-avatar>
          <div class="text-xs text-gray-500 dark:text-gray-400">
            <span class="font-medium text-gray-700 dark:text-gray-300">{{ comment.author.name }}</span>
            <app-time-ago [date]="comment.createdAt"></app-time-ago>
          </div>
        </div>
        <div class="mt-1 ml-9">
          <app-markdown-renderer [content]="comment.body"></app-markdown-renderer>
          <button (click)="replyTo(comment)" class="mt-1.5 inline-flex items-center gap-1 text-[11px] text-gray-500 dark:text-gray-400 hover:text-primary-600 dark:hover:text-primary-300 transition-colors">
            <svg class="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 10h10a8 8 0 018 8v2M3 10l6 6m-6-6l6-6"/>
            </svg>
            Reply
          </button>
        </div>
        <!-- Child comments (threaded replies) -->
        <div *ngIf="childComments(comment.id).length > 0" class="ml-9 mt-2 space-y-2 border-l-2 border-gray-100 dark:border-gray-700 pl-3">
          <div *ngFor="let child of childComments(comment.id)" class="py-1.5">
            <div class="flex items-center gap-2">
              <app-avatar [name]="child.author.name" [size]="20"></app-avatar>
              <div class="text-xs text-gray-500 dark:text-gray-400">
                <span class="font-medium text-gray-700 dark:text-gray-300">{{ child.author.name }}</span>
                <app-time-ago [date]="child.createdAt"></app-time-ago>
              </div>
            </div>
            <div class="mt-1 ml-7">
              <app-markdown-renderer [content]="child.body"></app-markdown-renderer>
              <button (click)="replyTo(child)" class="mt-1 inline-flex items-center gap-1 text-[11px] text-gray-500 dark:text-gray-400 hover:text-primary-600 dark:hover:text-primary-300 transition-colors">
                <svg class="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 10h10a8 8 0 018 8v2M3 10l6 6m-6-6l6-6"/>
                </svg>
                Reply
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="app-panel p-3 mt-4">
      <h3 class="text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase mb-2">
        {{ replyToAuthor() ? 'Reply to ' + replyToAuthor() : 'Add a comment' }}
      </h3>
      <textarea [(ngModel)]="replyBody" placeholder="Write a reply..." rows="2" class="w-full resize-none rounded border border-gray-200 dark:border-gray-700 dark:bg-steel-900 dark:text-steel-100 p-2 text-sm focus:border-primary-500 focus:ring-1 focus:ring-primary-500 outline-none"></textarea>
      <div class="flex items-center justify-end gap-2 mt-2">
        <button *ngIf="replyToCommentId()" (click)="cancelReply()" class="text-xs text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-200 transition-colors">Cancel reply</button>
        <button (click)="submitReply()" [disabled]="!replyBody.trim()" class="app-btn-primary disabled:opacity-50 disabled:cursor-not-allowed">
          {{ replyToCommentId() ? 'Post Reply' : 'Post Comment' }}
        </button>
      </div>
    </div>
  </ng-container>
</div>
