// src/components/Sidebar.tsx
import React, { useEffect, useState } from 'react';
import { NavLink } from 'react-router-dom';
import {
  Rss, MessageSquare, HelpCircle, MessagesSquare, CheckSquare, ListOrdered,
  FileCheck, Shield, Users, Sprout, GitBranch, Eye, BarChart3, Bot, FileCode,
  Calendar, CheckCircle2, Settings, Search as SearchIcon, Clock, FileText
} from 'lucide-react';
import { dataService } from '../services/dataService';
import { Counts } from '../types';
import { useRecentlyViewed } from '../context/RecentlyViewedContext';

export const Sidebar: React.FC = () => {
  const { recentlyViewed } = useRecentlyViewed();
  const [counts, setCounts] = useState<Counts>({
    forums: 0,
    posts: 0,
    threads: 0,
    toDoThreads: 0,
    comments: 0,
    workRequests: 0,
    requirements: 0,
    agendas: 0,
    candidates: 0,
    harvests: 0,
    openQuestions: 0,
    intents: 0,
    assessments: 0,
    observations: 0,
    agentRecords: 0,
    specifications: 0,
    plans: 0,
  });

  useEffect(() => {
    const update = () => setCounts(dataService.getCounts());
    update();
    const timer = setInterval(update, 3000);
    return () => clearInterval(timer);
  }, []);

  const sections = [
    {
      title: 'Communication',
      items: [
        { label: 'Feed', path: '/feed', icon: Rss, badge: counts.posts },
        { label: 'Forums', path: '/forums', icon: MessageSquare, badge: counts.forums },
        { label: 'To Do', path: '/todo', icon: CheckSquare, badge: counts.toDoThreads },
        { label: 'Open Questions', path: '/open-questions', icon: HelpCircle, badge: counts.openQuestions },
        { label: 'Resolutions', path: '/resolutions', icon: CheckCircle2 },
        { label: 'Conversations', path: '/conversations', icon: MessagesSquare },
      ],
    },
    {
      title: 'Requirements & Specs',
      items: [
        { label: 'Requirements', path: '/requirements', icon: CheckSquare, badge: counts.requirements },
        { label: 'Agendas', path: '/agendas', icon: Calendar, badge: counts.agendas },
        { label: 'Plans', path: '/plans', icon: ListOrdered, badge: counts.plans },
        { label: 'Specifications', path: '/specifications', icon: FileCheck, badge: counts.specifications },
        { label: 'Specs', path: '/specs', icon: FileCode },
      ],
    },
    {
      title: 'Work & Harvests',
      items: [
        { label: 'Work Requests', path: '/work-requests', icon: Shield, badge: counts.workRequests },
        { label: 'Candidates', path: '/candidates', icon: Users, badge: counts.candidates },
        { label: 'Harvests', path: '/harvests', icon: Sprout, badge: counts.harvests },
        { label: 'Intents', path: '/intents', icon: GitBranch, badge: counts.intents },
      ],
    },
    {
      title: 'Intelligence & Logs',
      items: [
        { label: 'Observations', path: '/observations', icon: Eye, badge: counts.observations },
        { label: 'Assessments', path: '/assessments', icon: BarChart3, badge: counts.assessments },
        { label: 'Agent Records', path: '/agent-records', icon: Bot, badge: counts.agentRecords },
        { label: 'Reports', path: '/reports', icon: BarChart3 },
      ],
    },
    {
      title: 'System',
      items: [
        { label: 'Search', path: '/search', icon: SearchIcon },
        { label: 'Settings', path: '/settings', icon: Settings },
      ],
    },
  ];

  return (
    <aside className="w-64 bg-slate-100/70 dark:bg-slate-900/95 border-r border-slate-200 dark:border-slate-800 flex flex-col h-[calc(100vh-3.5rem)] overflow-y-auto shrink-0 py-4 px-3 transition-colors">
      <div className="space-y-6">
        {sections.map((section) => (
          <div key={section.title} className="space-y-1">
            <h3 className="px-3 text-[10px] font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider font-mono">
              {section.title}
            </h3>
            <div className="mt-1 space-y-0.5">
              {section.items.map((item) => {
                const Icon = item.icon;
                return (
                  <NavLink
                    key={item.path}
                    to={item.path}
                    className={({ isActive }) =>
                      `flex items-center justify-between px-3 py-1.5 rounded-lg text-sm font-medium transition-colors ${
                        isActive
                          ? 'bg-indigo-600 text-white font-semibold shadow-sm'
                          : 'text-slate-600 dark:text-slate-300 hover:bg-slate-200/60 dark:hover:bg-slate-800 hover:text-slate-900 dark:hover:text-white'
                      }`
                    }
                  >
                    <div className="flex items-center gap-2.5">
                      <Icon className="w-4 h-4 shrink-0 opacity-80" />
                      <span>{item.label}</span>
                    </div>
                    {item.badge !== undefined && item.badge > 0 && (
                      <span className="px-1.5 py-0.2 text-[10px] font-mono font-bold rounded-full bg-slate-200/80 dark:bg-slate-800 text-slate-700 dark:text-indigo-300 border border-slate-300/80 dark:border-slate-700">
                        {item.badge}
                      </span>
                    )}
                  </NavLink>
                );
              })}
            </div>
          </div>
        ))}

        {recentlyViewed.length > 0 && (
          <div className="space-y-1 pt-2 border-t border-slate-200 dark:border-slate-800">
            <h3 className="px-3 text-[10px] font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider font-mono flex items-center justify-between">
              <span>Recently Viewed</span>
              <Clock className="w-3 h-3 text-indigo-500" />
            </h3>
            <div className="mt-1 space-y-0.5">
              {recentlyViewed.map((item) => (
                <NavLink
                  key={item.path}
                  to={item.path}
                  className={({ isActive }) =>
                    `flex items-center justify-between px-3 py-1.5 rounded-lg text-sm font-medium transition-colors group ${
                      isActive
                        ? 'bg-indigo-600/90 text-white font-semibold shadow-sm'
                        : 'text-slate-600 dark:text-slate-300 hover:bg-slate-200/60 dark:hover:bg-slate-800 hover:text-slate-900 dark:hover:text-white'
                    }`
                  }
                >
                  <div className="flex items-center gap-2 truncate">
                    <FileText className="w-3.5 h-3.5 shrink-0 opacity-70 group-hover:opacity-100" />
                    <span className="truncate">{item.title}</span>
                  </div>
                </NavLink>
              ))}
            </div>
          </div>
        )}
      </div>
    </aside>
  );

};

// src/app/components/sidebar/sidebar.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { Counts } from '../../services/data.service';
import { IconComponent } from '../icon/icon.component';

@Component({
  selector: 'app-sidebar',
  standalone: true,
  imports: [CommonModule, RouterLink, RouterLinkActive, IconComponent],
  templateUrl: './sidebar.component.html',
})
export class SidebarComponent {
  @Input() collapsed = false;
  @Input() counts: Counts | null = null;
  @Input() mobileOpen = false;
  @Output() closeMobile = new EventEmitter<void>();

  topItems = [
    { route: '/feed', label: 'Feed', icon: 'rss', countKey: 'posts' as keyof Counts },
    { route: '/forums', label: 'Forums', icon: 'users', countKey: 'forums' as keyof Counts },
  ];

  discoverItems = [
    { route: '/conversations', label: 'Conversations', icon: 'message-square-text', countKey: 'conversations' as keyof Counts },
    { route: '/harvests', label: 'Harvests', icon: 'database', countKey: 'harvests' as keyof Counts },
    { route: '/candidates', label: 'Candidates', icon: 'lightbulb', countKey: 'candidates' as keyof Counts },
  ];

  reasonItems = [
    { route: '/intents', label: 'Intent Records', icon: 'scroll-text', countKey: 'intents' as keyof Counts },
    { route: '/agendas', label: 'Agendas', icon: 'list-checks', countKey: 'agendas' as keyof Counts },
    { route: '/specifications', label: 'Specifications', icon: 'file-text', countKey: 'specifications' as keyof Counts },
    { route: '/specs', label: 'Spec Items', icon: 'file-text', countKey: 'specifications' as keyof Counts },
  ];

  executeItems = [
    { route: '/requirements', label: 'Requirements', icon: 'blocks', countKey: 'requirements' as keyof Counts },
    { route: '/work-requests', label: 'Work Requests', icon: 'git-branch', countKey: 'workRequests' as keyof Counts },
    { route: '/plans', label: 'Plans', icon: 'map', countKey: 'plans' as keyof Counts },
  ];

  adminItems = [
    { route: '/assessments', label: 'Assessments', icon: 'clipboard-check', countKey: 'assessments' as keyof Counts },
    { route: '/observations', label: 'Observations', icon: 'eye', countKey: 'observations' as keyof Counts },
    { route: '/reports', label: 'Reports', icon: 'bar-chart-3', countKey: 'reports' as keyof Counts },
    { route: '/agent-records', label: 'Agent Records', icon: 'bot', countKey: 'agentRecords' as keyof Counts },
  ];

  settingsItem = { route: '/settings', label: 'Settings', icon: 'settings' };

  openQuestionsGroup = [
    { route: '/open-questions', label: 'Open Questions', icon: 'help-circle', countKey: 'openQuestions' as keyof Counts },
    { route: '/resolutions', label: 'Resolutions', icon: 'check-circle', countKey: undefined as keyof Counts | undefined },
  ];

  getCount(key: keyof Counts): number | undefined {
    return this.counts ? this.counts[key] : undefined;
  }
}

<aside [class.w-56]="!collapsed" [class.w-14]="collapsed" class="h-full flex flex-col bg-steel-900 text-steel-300 border-r border-steel-800 transition-all duration-200">
  <div class="h-12 flex items-center px-4 border-b border-steel-800 flex-shrink-0 justify-between">
    <span class="font-semibold text-white text-sm tracking-tight" [class.hidden]="collapsed">Assembly</span>
    <span class="font-semibold text-white text-sm" [class.hidden]="!collapsed">A</span>
    @if (mobileOpen) {
      <button (click)="closeMobile.emit()" class="lg:hidden p-1 rounded text-steel-400 hover:text-white hover:bg-steel-800 transition-colors" aria-label="Close menu">
        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>
      </button>
    }
  </div>

  <nav class="flex-1 overflow-y-auto py-2 space-y-0.5 flex flex-col">
    @for (item of topItems; track item.route) {
      <a [routerLink]="item.route" routerLinkActive="bg-steel-800 text-white border-r-2 border-primary-400" class="group flex items-center gap-3 h-8 px-3 mx-2 rounded text-sm text-steel-400 hover:bg-steel-800 hover:text-white transition-colors duration-150">
        <app-icon [name]="item.icon" class="w-4 h-4 flex-shrink-0"></app-icon>
        <span [class.hidden]="collapsed" class="flex-1 truncate">{{ item.label }}</span>
        <span [class.hidden]="collapsed" *ngIf="counts" class="text-[10px] tabular-nums text-steel-500 bg-steel-800 px-1.5 py-0.5 rounded group-hover:text-steel-300">{{ getCount(item.countKey) }}</span>
      </a>
    }

    <div class="px-3 pt-4 pb-1" [class.hidden]="collapsed">
      <span class="text-[10px] font-semibold text-steel-500 uppercase tracking-wider">Discover</span>
    </div>
    @for (item of discoverItems; track item.route) {
      <a [routerLink]="item.route" routerLinkActive="bg-steel-800 text-white border-r-2 border-primary-400" class="group flex items-center gap-3 h-8 px-3 mx-2 rounded text-sm text-steel-400 hover:bg-steel-800 hover:text-white transition-colors duration-150">
        <app-icon [name]="item.icon" class="w-4 h-4 flex-shrink-0"></app-icon>
        <span [class.hidden]="collapsed" class="flex-1 truncate">{{ item.label }}</span>
        <span [class.hidden]="collapsed" *ngIf="counts" class="text-[10px] tabular-nums text-steel-500 bg-steel-800 px-1.5 py-0.5 rounded group-hover:text-steel-300">{{ getCount(item.countKey) }}</span>
      </a>
    }

    <div class="px-3 pt-4 pb-1" [class.hidden]="collapsed">
      <span class="text-[10px] font-semibold text-steel-500 uppercase tracking-wider">Open Questions</span>
    </div>
    @for (item of openQuestionsGroup; track item.route) {
      <a [routerLink]="item.route" routerLinkActive="bg-steel-800 text-white border-r-2 border-primary-400" class="group flex items-center gap-3 h-8 px-3 mx-2 rounded text-sm text-steel-400 hover:bg-steel-800 hover:text-white transition-colors duration-150">
        <app-icon [name]="item.icon" class="w-4 h-4 flex-shrink-0"></app-icon>
        <span [class.hidden]="collapsed" class="flex-1 truncate">{{ item.label }}</span>
        <span [class.hidden]="collapsed" *ngIf="counts && item.countKey" class="text-[10px] tabular-nums text-steel-500 bg-steel-800 px-1.5 py-0.5 rounded group-hover:text-steel-300">{{ getCount(item.countKey!) }}</span>
      </a>
    }

    <div class="px-3 pt-4 pb-1" [class.hidden]="collapsed">
      <span class="text-[10px] font-semibold text-steel-500 uppercase tracking-wider">Reason</span>
    </div>
    @for (item of reasonItems; track item.route) {
      <a [routerLink]="item.route" routerLinkActive="bg-steel-800 text-white border-r-2 border-primary-400" class="group flex items-center gap-3 h-8 px-3 mx-2 rounded text-sm text-steel-400 hover:bg-steel-800 hover:text-white transition-colors duration-150">
        <app-icon [name]="item.icon" class="w-4 h-4 flex-shrink-0"></app-icon>
        <span [class.hidden]="collapsed" class="flex-1 truncate">{{ item.label }}</span>
        <span [class.hidden]="collapsed" *ngIf="counts" class="text-[10px] tabular-nums text-steel-500 bg-steel-800 px-1.5 py-0.5 rounded group-hover:text-steel-300">{{ getCount(item.countKey) }}</span>
      </a>
    }

    <div class="px-3 pt-4 pb-1" [class.hidden]="collapsed">
      <span class="text-[10px] font-semibold text-steel-500 uppercase tracking-wider">Execute</span>
    </div>
    @for (item of executeItems; track item.route) {
      <a [routerLink]="item.route" routerLinkActive="bg-steel-800 text-white border-r-2 border-primary-400" class="group flex items-center gap-3 h-8 px-3 mx-2 rounded text-sm text-steel-400 hover:bg-steel-800 hover:text-white transition-colors duration-150">
        <app-icon [name]="item.icon" class="w-4 h-4 flex-shrink-0"></app-icon>
        <span [class.hidden]="collapsed" class="flex-1 truncate">{{ item.label }}</span>
        <span [class.hidden]="collapsed" *ngIf="counts" class="text-[10px] tabular-nums text-steel-500 bg-steel-800 px-1.5 py-0.5 rounded group-hover:text-steel-300">{{ getCount(item.countKey) }}</span>
      </a>
    }

    <div class="px-3 pt-4 pb-1" [class.hidden]="collapsed">
      <span class="text-[10px] font-semibold text-steel-500 uppercase tracking-wider">Admin</span>
    </div>
    @for (item of adminItems; track item.route) {
      <a [routerLink]="item.route" routerLinkActive="bg-steel-800 text-white border-r-2 border-primary-400" class="group flex items-center gap-3 h-8 px-3 mx-2 rounded text-sm text-steel-400 hover:bg-steel-800 hover:text-white transition-colors duration-150">
        <app-icon [name]="item.icon" class="w-4 h-4 flex-shrink-0"></app-icon>
        <span [class.hidden]="collapsed" class="flex-1 truncate">{{ item.label }}</span>
        <span [class.hidden]="collapsed" *ngIf="counts" class="text-[10px] tabular-nums text-steel-500 bg-steel-800 px-1.5 py-0.5 rounded group-hover:text-steel-300">{{ getCount(item.countKey) }}</span>
      </a>
    }

    <div class="mt-auto pt-2">
      <a [routerLink]="settingsItem.route" routerLinkActive="bg-steel-800 text-white border-r-2 border-primary-400" class="group flex items-center gap-3 h-8 px-3 mx-2 rounded text-sm text-steel-400 hover:bg-steel-800 hover:text-white transition-colors duration-150">
        <app-icon [name]="settingsItem.icon" class="w-4 h-4 flex-shrink-0"></app-icon>
        <span [class.hidden]="collapsed" class="flex-1 truncate">{{ settingsItem.label }}</span>
      </a>
    </div>
  </nav>
</aside>
